steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/insights-travelintelligence:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/insights-travelintelligence:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/insights-travelintelligence:$BUILD_ID'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'travelintelligence-insights-site'
      - '--image'
      - 'gcr.io/$PROJECT_ID/insights-travelintelligence:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3002'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,USE_FIRESTORE=true,RP_ID=insights.travelintelligence.club,RP_NAME=Travel Intelligence Club Insights,ORIGIN=https://insights.travelintelligence.club,BASE_URL=https://insights.travelintelligence.club,GHOST_API_URL=https://insights.travelintelligence.club,GCP_PROJECT_ID=$PROJECT_ID,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,ALLOWED_LABELS=builder^:^patron^:^buccaneer^:^explorer^:^insights-subscriber'
      - '--set-secrets'
      - 'SESSION_SECRET=SESSION_SECRET:latest,BREVO_API_KEY=BREVO_API_KEY:latest,BREVO_FROM_EMAIL=BREVO_FROM_EMAIL:latest,BREVO_FROM_NAME=BREVO_FROM_NAME:latest,GHOST_ADMIN_API_KEY=GHOST_ADMIN_API_KEY:latest'

images:
  - 'gcr.io/$PROJECT_ID/insights-travelintelligence:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/insights-travelintelligence:latest'

timeout: '1200s'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
